### ISSUE TITLE
Provide .Net Standard version for .Net Core 3.0 WPF

### ISSUE THREAD

**Issue by andyesys** [ptv-logistics/xserver.net#16]
When referencing this package from a .Net Standard 2.1 project, the following warning is generated:

> Warnung	NU1701
> 
> Das Paket "Ptv.XServer.Net 1.7.4" wurde nicht mit dem Projektzielframework ".NETStandard,Version=v2.1", sondern mit ".NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8" wiederhergestellt. Dieses Paket ist mit Ihrem Projekt möglicherweise nicht vollständig kompatibel.

**Comment by oliverheilig** [comment]
Hi,

xServer.NET is a spin-off from a framework we use to build our Windows line-of-business applications. It heavyly relies on the features of the .NET framework (there was a Silverlight version once though https://github.com/oliverheilig/SilverMap :smirk:).  

Technically it would be possible to port some classes to Core or make some parts Standard-conform, but this would require a major redesign.

Meanwhile we have moved over to browser-based applications and abandoned the Microsoft UI stack, and honestly i think this is also the plan of Microsoft.

So we don't have any plans to extend the control for other .NET variants. I have some kind of summary on the options for LOB applications in this thread https://xserver.ptvgroup.com/forum/viewtopic.php?f=5&t=1082#p3198

Oli

**Comment by andyesys** [comment]
Hello, Oliver. Thank you for your detailed explanation. I'll look around for other options. The ticket can be closed then probably also.

**Comment by oliverheilig** [comment]
Hi @andyesys,

i have added a stripped-down version on https://github.com/oliverheilig/XServer.Core. If you just want some basic "slippy map" functions for WPF.Core, this could do it.

Oli

**Comment by andyesys** [comment]
I have switched to https://github.com/ClemensFischer/XAML-Map-Control which also provides a .net core wpf version.
