### ISSUE TITLE
Reference to Ptv.Components.Projections.dll missing

### ISSUE THREAD

**Issue by MFinkBK** [ptv-logistics/xserver.net#17]
I'm trying to migrate my project from using the PTV xServer .NET assemblies as standalone files to using the NuGet package. This works for projects that only reference Ptv.XServer.Controls.Map.dll. I also have some projects that are using transformation and are using Ptv.Components.Projections.dll. I think the .nuspec file is just missing a second `<reference file="Ptv.Components.Projections.dll" />` line.

**Comment by oliverheilig** [comment]
Hello, this was by intention since the majority of users don't require the projections-library, and it is only "soft-linked" inside the control. So if you need a layer which requires reprojection, you have to add the reference to the dll inside the package folder explicitly.

**Comment by MFinkBK** [comment]
Thanks for the info. The projects that only reference `Ptv.XServer.Controls.Map.dll` don't have the `Ptv.Components.Projections.dll` file in the `bin\Debug` (or `bin\Release`) folder. Looking at the references of `Ptv.XServer.Controls.Map.dll`, the `Ptv.Components.Projections.dll` is listed, though. So the missing `Ptv.Components.Projections.dll` should already give me an exception when loading the assembly. Or what do you mean with soft-linked?`
Adding a fixed reference into the NuGet package folder directly is non-portable, since it's located somewhere in the user's folder (`C:\Users\username\.nuget\packages\ptv.xserver.net\1.7.6\lib`). So that's not an ideal solution...

**Comment by oliverheilig** [comment]
I have validated the samples on https://github.com/ptv-logistics/xserver.net-samples and the Ptv.Components.Projections.dll is always copied to the bin folder, to gether with the XmlSerialzers.dll. So the only reason you would need an explicit reference is when you need to access any projections classes in your code explicitly.

Hover, i could add the reference to the nuget package with the next release.

**Comment by MFinkBK** [comment]
I checked our code, and in some places we use `Ptv.Components.Projections.CoordinateReferenceSystem` to get coordinate reference systems to convert to or from other coordinate systems (e.g. ETRS89 via a Proj4 transform string). So it would be good, at least for us, if the NuGet package would have that assembly, too. Thanks!

**Comment by oliverheilig** [comment]
The reference is now added with the latest release https://www.nuget.org/packages/Ptv.XServer.Net/1.7.7

**Comment by MFinkBK** [comment]
Thank you! One more question... Previously I had the additional files `Ptv.XServer.Controls.Map.XmlSerializers.dll` and `de\Ptv.XServer.Controls.Map.resources.dll` that are not placed in the bin folder at build time. Are they still necessary for the SDK to work?

**Comment by oliverheilig** [comment]
That's weird. They are not really required, but should be correctly copied. Tested it with a WinForms-App and getting

<de>
Ptv.Components.Projections.dll
Ptv.Components.Projections.pdb
Ptv.Components.Projections.xml
Ptv.XServer.Controls.Map.dll
Ptv.XServer.Controls.Map.pdb
Ptv.XServer.Controls.Map.xml
Ptv.XServer.Controls.Map.XmlSerializers.dll
TestApp.exe
TestApp.exe.config
TestApp.pdb

**Comment by MFinkBK** [comment]
Ok, thanks! I will also retest, maybe I've got something wrong.

**Comment by MFinkBK** [comment]
I tested with version 1.7.10 and the bug is gone.
