### ISSUE TITLE
Feature Layer for PTV_TrafficIncidents

### ISSUE THREAD

**Issue by MFinkBK** [ptv-logistics/xserver.net#20]
I'm currently studying the xserver.net code to find out how to display the traffic incidents feature layer. I'm using PTV xServer 2 and set the `XMapUrl`. After that I try to set the feature layer properties, but the map doesn't show any features:

```
    map.Xmap2LayerFactory.FeatureLayers.ReferenceTime =
        DateTimeOffset.Now.ToString("o", CultureInfo.InvariantCulture);

    map.Xmap2LayerFactory.FeatureLayers.TimeConsiderationScenario =
        "SnapshotTimeConsideration";
```

Am I missing something here? Thanks!

**Comment by oliverheilig** [comment]
Hi, have you checked the reference-implementation? 

https://github.com/ptv-logistics/xserver.net-samples/tree/master/Xmap2LayerFactoryTest

There the specific parameters are set.

**Comment by MFinkBK** [comment]
Thanks, I didn't knew that repository yet! From studying that code, the missing line was:

    layerFactory.LabelThemes.Add("PTV_TrafficIncidents");
